# Generated by Django 4.1 on 2022-09-21 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='id_profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='App.profesores'),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='id_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='App.cursos'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='id_estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='App.estudiantes'),
        ),
    ]
